# Generated by Django 4.0.4 on 2022-05-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='legal_basis',
            field=models.TextField(),
        ),
    ]
