# Generated by Django 4.0.4 on 2022-05-31 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maps",
            name="subway_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
