# Generated by Django 4.0.4 on 2022-05-31 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0003_maps_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryofMaps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Choice Category of Map",
                "verbose_name_plural": "Choice Categories of Maps",
                "db_table": "category_of_maps",
            },
        ),
        migrations.AlterField(
            model_name="maps",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="maps.categoryofmaps",
            ),
        ),
    ]
