# Generated by Django 4.0.4 on 2022-05-31 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_categoryofmaps_alter_maps_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maps',
            name='category',
        ),
    ]
