# Generated by Django 4.0.4 on 2022-05-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_maps_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryofmaps',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='categoryofmaps',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='categoryofmaps',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maps',
            name='address_description_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maps',
            name='address_description_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maps',
            name='address_description_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maps',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maps',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maps',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
