# Generated by Django 4.0.4 on 2022-05-31 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_news_views_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "New",
                "verbose_name_plural": "News",
            },
        ),
        migrations.AlterModelTable(
            name="news",
            table="news",
        ),
    ]
